services:
  api:
    image: task-list
    build: .
    container_name: task-list-api
    environment:
      DATABASE_URL: postgresql://docker:docker@db:5432/task_list?schema=public
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - task-list
    restart: on-failure

  db:
    image: postgres:17-alpine
    container_name: task-list-db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: task_list
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-list
    restart: always

volumes:
  postgres_data:
networks:
  task-list:
